# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This file is auto generated by the elixir code generator program.
# Do not edit this file manually.

defmodule GoogleApi.Translate.V3.Api.Detections do
  @moduledoc """
  API calls for all endpoints tagged `Detections`.
  """

  alias GoogleApi.Translate.V3.Connection
  alias GoogleApi.Gax.{Request, Response}

  @library_version Mix.Project.config() |> Keyword.get(:version, "")

  @doc """
  Detects the language of text within a request.

  ## Parameters

  *   `connection` (*type:* `GoogleApi.Translate.V3.Connection.t`) - Connection to server
  *   `project_id` (*type:* `String.t`) - Your GCP project ID
  *   `optional_params` (*type:* `keyword()`) - Optional parameters
      *   `:"$.xgafv"` (*type:* `String.t`) - V1 error format.
      *   `:access_token` (*type:* `String.t`) - OAuth access token.
      *   `:alt` (*type:* `String.t`) - Data format for response.
      *   `:bearer_token` (*type:* `String.t`) - OAuth bearer token.
      *   `:callback` (*type:* `String.t`) - JSONP
      *   `:fields` (*type:* `String.t`) - Selector specifying which fields to include in a partial response.
      *   `:oauth_token` (*type:* `String.t`) - OAuth 2.0 token for the current user.
      *   `:pp` (*type:* `boolean()`) - Pretty-print response.
      *   `:prettyPrint` (*type:* `boolean()`) - Returns response with indentations and line breaks.
      *   `:quotaUser` (*type:* `String.t`) - Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters. Overrides userIp if both are provided.
      *   `:body` (*type:* `GoogleApi.Translate.V3.Model.DetectLanguageRequest.t`) -
  *   `opts` (*type:* `keyword()`) - Call options

  ## Returns

  *   `{:ok, %GoogleApi.Translate.V3.Model.DetectionsListResponse{}}` on success
  *   `{:error, info}` on failure
  """
  @spec language_detections_detect(Tesla.Env.client(), keyword(), keyword()) ::
          {:ok, GoogleApi.Translate.V3.Model.DetectionsListResponse.t()} | {:error, Tesla.Env.t()}
  def language_detections_detect(connection, project_id, optional_params \\ [], opts \\ []) do
    optional_params_config = %{
      :"$.xgafv" => :query,
      :access_token => :query,
      :alt => :query,
      :bearer_token => :query,
      :callback => :query,
      :fields => :query,
      :oauth_token => :query,
      :pp => :query,
      :prettyPrint => :query,
      :quotaUser => :query,
      :body => :body
    }

    request =
      Request.new()
      |> Request.method(:post)
      |> Request.url("/v3beta1/projects/#{project_id}/locations/global:detectLanguage", %{})
      |> Request.add_optional_params(optional_params_config, optional_params)
      |> Request.library_version(@library_version)

    connection
    |> Connection.execute(request)
    |> Response.decode(
      opts ++ [struct: %GoogleApi.Translate.V3.Model.DetectionsListResponse{}, data_wrapped: true]
    )
  end
end
